####
POST http://localhost:8000/notification/generator
Content-Type: application/json

{
  "infoUser": "noemibarca_64@gmail.com",
  "title": "Mensagem API de kakau",
  "type": "E",
  "message": "Sua best mandou lembrança"
}
####
POST http://localhost:8000/notification/generator
Content-Type: application/json

{
  "infoUser": "botelhojulia62@gmail.com",
  "title": "Só para abusar mesmoo",
  "type": "E",
  "message": "xoxo da piupiu, kkkkkkk"
}
####
POST http://localhost:8000/notification/generator
Content-Type: application/json

{
  "infoUser":"fcf",
  "title": "Encomenda atrasada",
  "type": "W",
  "message": "Ciclano sua encomenda atrasou"
}
####
POST http://localhost:8000/notification/generator
Content-Type: application/json

{
  "infoUser": "kauvergasta12@gmail.com",
  "title": "Encomenda chegou",
  "type": "E" ,
  "message": "Fulana sua encomenda chegou"
}
####
POST http://localhost:8000/notification/generator
Content-Type: application/json

{
  "title": "Encomenda Adiada novamente",
  "type": "S" ,
  "message": "José Almeida, ocorreu a tentativa de entrega, mas ninguém recebeu"
}
###
GET http://localhost:8000/notification/listNotifications
###
DELETE  http://localhost:8000/notification/c7220cfc-caaa-4bc8-9bf6-17058b051df7
###
GET http://localhost:8000/notification/listChannels
###
GET http://localhost:8000/h2-console

