####
POST http://localhost:8000/notification/generator
Content-Type: application/json

{
  "infoUser": "kauvrgst@gmail.com",
  "title": "Controller",
  "type": "E" ,
  "message": "http://files.cod3r.com.br/apostila-docker.pdf,https://insightlab.ufc.br/wp-content/uploads/2020/05/Introdu%C3%A7%C3%A3o-a-Docker-compactado.pdf,https://labex.io/learn/docker "
}
####
POST http://localhost:8000/stream/kafka
Content-Type: application/json

{
  "infoUser": "kauvrgst@gmail.com",
  "title": "Kafka - status",
  "type": "E" ,
  "message": "Teste"
}
###
POST http://localhost:8000/stream/kafka
Content-Type: application/json

{
  "infoUser": "kauvrgst@gmail.com",
  "title": "sei la",
  "type": "E" ,
  "message": "teste"
}
####
POST http://localhost:8000/stream/kafka
Content-Type: application/json

{
  "infoUser": "notif.hub@outlook.com",
  "title": "SMTP - Outlook",
  "type": "E" ,
  "message": "Outlook teste",
  "status": "PENDING"

}

###
GET http://localhost:8000/notification/listNotifications
###
DELETE  http://localhost:8000/notification/ffbe5f53-a834-4328-9a69-73376c0f3a64
###
GET   http://localhost:8000/notification/61cf1fa4-c7a7-43bc-bd49-117c7151f7e6
###
GET http://localhost:8000/notification/listChannels
###
GET http://localhost:8000/h2-console

